<?php
declare(strict_types=1);
// GENERATED by bin/codegen.php - DO NOT EDIT. Edit schema/business.schema.json and regenerate.
namespace HoV2\Domain;

/**
 * The canonical Business object. The ONLY shape data takes inside HO v2.
 * Renderers, scorers, and gap detection consume this and nothing else.
 */
final class Business
{
    public function __construct(
        public readonly int $id,
        public readonly string $uid,
        public readonly string $slug,
        public readonly string $name,
        public readonly string $category,
        public readonly string $city,
        public readonly string $state,
        public readonly string $pipelineStatus,
        public readonly ?string $email,
        public readonly ?string $phone,
        public readonly ?string $websiteUrl,
        public readonly ?string $facebookUrl,
        public readonly ?string $ownerFirstName,
        /** @var array<string,mixed> validated business_profile row */
        private readonly array $profile,
    ) {}

    public function get(string $field): mixed
    {
        if (!array_key_exists($field, $this->profile)) { throw new \InvalidArgumentException("Unknown profile field: {$field}"); }
        return $this->profile[$field];
    }

    public function isVerified(): bool { return $this->profile['verified_at'] !== null; }

    public function hasWebsite(): ?bool { return $this->profile['has_website'] ?? null; }
    public function websiteQuality(): ?string { return $this->profile['website_quality'] ?? null; }
    public function websiteNotes(): ?string { return $this->profile['website_notes'] ?? null; }
    public function websiteConfidence(): ?string { return $this->profile['website_confidence'] ?? null; }
    public function hasContactForm(): ?bool { return $this->profile['has_contact_form'] ?? null; }
    public function hasOnlineBooking(): ?bool { return $this->profile['has_online_booking'] ?? null; }
    public function hasPhotoGallery(): ?bool { return $this->profile['has_photo_gallery'] ?? null; }
    public function hasAboutPage(): ?bool { return $this->profile['has_about_page'] ?? null; }
    public function hasFaqPage(): ?bool { return $this->profile['has_faq_page'] ?? null; }
    public function hasPricingPage(): ?bool { return $this->profile['has_pricing_page'] ?? null; }
    public function hasVideoOnSite(): ?bool { return $this->profile['has_video_on_site'] ?? null; }
    public function hasOnlinePayment(): ?bool { return $this->profile['has_online_payment'] ?? null; }
    public function siteAppearsOutdated(): ?bool { return $this->profile['site_appears_outdated'] ?? null; }
    public function hasBlog(): ?bool { return $this->profile['has_blog'] ?? null; }
    public function hasTestimonialsSection(): ?bool { return $this->profile['has_testimonials_section'] ?? null; }
    public function hasLiveChat(): ?bool { return $this->profile['has_live_chat'] ?? null; }
    public function mobileFriendly(): ?bool { return $this->profile['mobile_friendly'] ?? null; }
    public function hasSsl(): ?bool { return $this->profile['has_ssl'] ?? null; }
    public function hasGoogleBusiness(): ?bool { return $this->profile['has_google_business'] ?? null; }
    public function googleReviewCount(): ?int { return $this->profile['google_review_count'] ?? null; }
    public function googleRating(): ?float { return $this->profile['google_rating'] ?? null; }
    public function googleNotes(): ?string { return $this->profile['google_notes'] ?? null; }
    public function hasGbpPosts(): ?bool { return $this->profile['has_gbp_posts'] ?? null; }
    public function gbpServicesListed(): ?bool { return $this->profile['gbp_services_listed'] ?? null; }
    public function gbpHoursListed(): ?bool { return $this->profile['gbp_hours_listed'] ?? null; }
    public function gbpPhotoCount(): ?int { return $this->profile['gbp_photo_count'] ?? null; }
    public function respondsToReviews(): ?bool { return $this->profile['responds_to_reviews'] ?? null; }
    public function lastReviewDate(): ?string { return $this->profile['last_review_date'] ?? null; }
    public function reviewQuote1(): ?string { return $this->profile['review_quote_1'] ?? null; }
    public function reviewQuote1Author(): ?string { return $this->profile['review_quote_1_author'] ?? null; }
    public function reviewQuote1Date(): ?string { return $this->profile['review_quote_1_date'] ?? null; }
    public function reviewQuote2(): ?string { return $this->profile['review_quote_2'] ?? null; }
    public function reviewQuote2Author(): ?string { return $this->profile['review_quote_2_author'] ?? null; }
    public function reviewQuote2Date(): ?string { return $this->profile['review_quote_2_date'] ?? null; }
    public function hasFacebook(): ?bool { return $this->profile['has_facebook'] ?? null; }
    public function facebookActivity(): ?string { return $this->profile['facebook_activity'] ?? null; }
    public function facebookNotes(): ?string { return $this->profile['facebook_notes'] ?? null; }
    public function facebookPageType(): ?string { return $this->profile['facebook_page_type'] ?? null; }
    public function facebookLastPostMonths(): ?int { return $this->profile['facebook_last_post_months'] ?? null; }
    public function facebookFollowerBand(): ?string { return $this->profile['facebook_follower_band'] ?? null; }
    public function facebookHasCtaButton(): ?bool { return $this->profile['facebook_has_cta_button'] ?? null; }
    public function hasInstagram(): ?bool { return $this->profile['has_instagram'] ?? null; }
    public function instagramActivity(): ?string { return $this->profile['instagram_activity'] ?? null; }
    public function instagramIsBusiness(): ?bool { return $this->profile['instagram_is_business'] ?? null; }
    public function instagramFollowerBand(): ?string { return $this->profile['instagram_follower_band'] ?? null; }
    public function instagramLastPostMonths(): ?int { return $this->profile['instagram_last_post_months'] ?? null; }
    public function hasYelp(): ?bool { return $this->profile['has_yelp'] ?? null; }
    public function yelpClaimed(): ?bool { return $this->profile['yelp_claimed'] ?? null; }
    public function yelpReviewCount(): ?int { return $this->profile['yelp_review_count'] ?? null; }
    public function yelpRating(): ?float { return $this->profile['yelp_rating'] ?? null; }
    public function hasAngi(): ?bool { return $this->profile['has_angi'] ?? null; }
    public function hasThumbtack(): ?bool { return $this->profile['has_thumbtack'] ?? null; }
    public function hasYoutube(): ?bool { return $this->profile['has_youtube'] ?? null; }
    public function hasNextdoorListing(): ?bool { return $this->profile['has_nextdoor_listing'] ?? null; }
    public function hasBbbListing(): ?bool { return $this->profile['has_bbb_listing'] ?? null; }
    public function logoQuality(): ?string { return $this->profile['logo_quality'] ?? null; }
    public function hasBeforeAfterPhotos(): ?bool { return $this->profile['has_before_after_photos'] ?? null; }
    public function hasProfessionalEmail(): ?bool { return $this->profile['has_professional_email'] ?? null; }
    public function isLicensedInsuredVisible(): ?bool { return $this->profile['is_licensed_insured_visible'] ?? null; }
    public function hasServiceGuarantee(): ?bool { return $this->profile['has_service_guarantee'] ?? null; }
    public function servicesList(): array { return json_decode((string)($this->profile['services_list'] ?? '[]'), true) ?: []; }
    public function serviceAreaText(): ?string { return $this->profile['service_area_text'] ?? null; }
    public function bookingMethod(): ?string { return $this->profile['booking_method'] ?? null; }
    public function yearsInBusiness(): ?int { return $this->profile['years_in_business'] ?? null; }
    public function ownerAgeBand(): ?string { return $this->profile['owner_age_band'] ?? null; }
    public function targetCustomerType(): ?string { return $this->profile['target_customer_type'] ?? null; }
    public function isFranchise(): ?bool { return $this->profile['is_franchise'] ?? null; }
    public function competitorHasWebsite(): ?bool { return $this->profile['competitor_has_website'] ?? null; }
    public function competitorName(): ?string { return $this->profile['competitor_name'] ?? null; }
    public function competitorWebsite(): ?string { return $this->profile['competitor_website'] ?? null; }
    public function competitorGoogleRating(): ?float { return $this->profile['competitor_google_rating'] ?? null; }
    public function competitorReviewCount(): ?int { return $this->profile['competitor_review_count'] ?? null; }
    public function opportunitySummary(): ?string { return $this->profile['opportunity_summary'] ?? null; }
    public function strengths(): array { return json_decode((string)($this->profile['strengths'] ?? '[]'), true) ?: []; }
    public function gaps(): array { return json_decode((string)($this->profile['gaps'] ?? '[]'), true) ?: []; }
    public function recommendedPackage(): ?string { return $this->profile['recommended_package'] ?? null; }
}
