<?php
declare(strict_types=1);
// GENERATED by bin/codegen.php - DO NOT EDIT. Edit schema/business.schema.json and regenerate.
namespace HoV2\Import;

final class Validator
{
    /** @return array{0: array<string,mixed>, 1: string[]} [clean row, rejection reasons (non-empty = reject record)] */
    public static function validate(array $in): array
    {
        $out = []; $reject = [];
        $hasWebsite = (bool)($in['has_website'] ?? false);
        if ((bool)($in['is_franchise'] ?? false)) { $reject[] = 'franchise: auto-excluded'; }
        if (($in['website_confidence'] ?? '') === 'low') { $in['website_url'] = ''; }
        // has_website (bool)
        $out['has_website'] = (bool)($in['has_website'] ?? false);
        // website_quality (enum)
        $out['website_quality'] = in_array(($in['website_quality'] ?? ''), ['none','poor','basic','decent'], true) ? $in['website_quality'] : 'none';
        // website_notes (text)
        $out['website_notes'] = mb_substr(trim((string)($in['website_notes'] ?? '')), 0, 65000);
        // website_confidence (enum)
        $out['website_confidence'] = in_array(($in['website_confidence'] ?? ''), ['high','medium','low'], true) ? $in['website_confidence'] : 'high';
        // has_contact_form (bool)
        $out['has_contact_form'] = !$hasWebsite ? null : (isset($in['has_contact_form']) ? (bool)$in['has_contact_form'] : null);
        // has_online_booking (bool)
        $out['has_online_booking'] = !$hasWebsite ? null : (isset($in['has_online_booking']) ? (bool)$in['has_online_booking'] : null);
        // has_photo_gallery (bool)
        $out['has_photo_gallery'] = !$hasWebsite ? null : (isset($in['has_photo_gallery']) ? (bool)$in['has_photo_gallery'] : null);
        // has_about_page (bool)
        $out['has_about_page'] = !$hasWebsite ? null : (isset($in['has_about_page']) ? (bool)$in['has_about_page'] : null);
        // has_faq_page (bool)
        $out['has_faq_page'] = !$hasWebsite ? null : (isset($in['has_faq_page']) ? (bool)$in['has_faq_page'] : null);
        // has_pricing_page (bool)
        $out['has_pricing_page'] = !$hasWebsite ? null : (isset($in['has_pricing_page']) ? (bool)$in['has_pricing_page'] : null);
        // has_video_on_site (bool)
        $out['has_video_on_site'] = !$hasWebsite ? null : (isset($in['has_video_on_site']) ? (bool)$in['has_video_on_site'] : null);
        // has_online_payment (bool)
        $out['has_online_payment'] = !$hasWebsite ? null : (isset($in['has_online_payment']) ? (bool)$in['has_online_payment'] : null);
        // site_appears_outdated (bool)
        $out['site_appears_outdated'] = !$hasWebsite ? null : (isset($in['site_appears_outdated']) ? (bool)$in['site_appears_outdated'] : null);
        // has_blog (bool)
        $out['has_blog'] = !$hasWebsite ? null : (isset($in['has_blog']) ? (bool)$in['has_blog'] : null);
        // has_testimonials_section (bool)
        $out['has_testimonials_section'] = !$hasWebsite ? null : (isset($in['has_testimonials_section']) ? (bool)$in['has_testimonials_section'] : null);
        // has_live_chat (bool)
        $out['has_live_chat'] = !$hasWebsite ? null : (isset($in['has_live_chat']) ? (bool)$in['has_live_chat'] : null);
        // mobile_friendly (bool)
        $out['mobile_friendly'] = !$hasWebsite ? null : (isset($in['mobile_friendly']) ? (bool)$in['mobile_friendly'] : null);
        // has_ssl (bool)
        $out['has_ssl'] = !$hasWebsite ? null : (isset($in['has_ssl']) ? (bool)$in['has_ssl'] : null);
        // has_google_business (bool)
        $out['has_google_business'] = (bool)($in['has_google_business'] ?? false);
        // google_review_count (int)
        $out['google_review_count'] = max(0, (int)($in['google_review_count'] ?? 0));
        // google_rating (decimal)
        $out['google_rating'] = min(5.0, max(0.0, (float)($in['google_rating'] ?? 0)));
        // google_notes (text)
        $out['google_notes'] = mb_substr(trim((string)($in['google_notes'] ?? '')), 0, 65000);
        // has_gbp_posts (bool)
        $out['has_gbp_posts'] = isset($in['has_gbp_posts']) ? (bool)$in['has_gbp_posts'] : null;
        // gbp_services_listed (bool)
        $out['gbp_services_listed'] = isset($in['gbp_services_listed']) ? (bool)$in['gbp_services_listed'] : null;
        // gbp_hours_listed (bool)
        $out['gbp_hours_listed'] = isset($in['gbp_hours_listed']) ? (bool)$in['gbp_hours_listed'] : null;
        // gbp_photo_count (int)
        $out['gbp_photo_count'] = isset($in['gbp_photo_count']) && $in['gbp_photo_count'] !== '' ? ((int)$in['gbp_photo_count']) : null;
        // responds_to_reviews (bool)
        $out['responds_to_reviews'] = (bool)($in['responds_to_reviews'] ?? false);
        // last_review_date (yearmonth)
        $out['last_review_date'] = preg_match('/^\d{4}-\d{2}$/', (string)($in['last_review_date'] ?? '')) ? $in['last_review_date'] : null;
        // review_quote_1 (text)
        $out['review_quote_1'] = mb_substr(trim((string)($in['review_quote_1'] ?? '')), 0, 65000);
        if (str_word_count($out['review_quote_1']) > 40) { $out['review_quote_1'] = ''; } // over word cap = drop, never trim a verbatim quote
        // review_quote_1_author (string)
        $out['review_quote_1_author'] = mb_substr(trim((string)($in['review_quote_1_author'] ?? '')), 0, 255);
        // review_quote_1_date (yearmonth)
        $out['review_quote_1_date'] = preg_match('/^\d{4}-\d{2}$/', (string)($in['review_quote_1_date'] ?? '')) ? $in['review_quote_1_date'] : null;
        // review_quote_2 (text)
        $out['review_quote_2'] = mb_substr(trim((string)($in['review_quote_2'] ?? '')), 0, 65000);
        if (str_word_count($out['review_quote_2']) > 40) { $out['review_quote_2'] = ''; } // over word cap = drop, never trim a verbatim quote
        // review_quote_2_author (string)
        $out['review_quote_2_author'] = mb_substr(trim((string)($in['review_quote_2_author'] ?? '')), 0, 255);
        // review_quote_2_date (yearmonth)
        $out['review_quote_2_date'] = preg_match('/^\d{4}-\d{2}$/', (string)($in['review_quote_2_date'] ?? '')) ? $in['review_quote_2_date'] : null;
        // has_facebook (bool)
        $out['has_facebook'] = (bool)($in['has_facebook'] ?? false);
        // facebook_activity (enum)
        $out['facebook_activity'] = in_array(($in['facebook_activity'] ?? ''), ['none','dormant','active'], true) ? $in['facebook_activity'] : 'none';
        // facebook_notes (text)
        $out['facebook_notes'] = mb_substr(trim((string)($in['facebook_notes'] ?? '')), 0, 65000);
        // facebook_page_type (enum)
        $out['facebook_page_type'] = in_array(($in['facebook_page_type'] ?? ''), ['none','personal','business'], true) ? $in['facebook_page_type'] : 'none';
        // facebook_last_post_months (int)
        $out['facebook_last_post_months'] = isset($in['facebook_last_post_months']) && $in['facebook_last_post_months'] !== '' ? ((int)$in['facebook_last_post_months']) : null;
        // facebook_follower_band (enum)
        $out['facebook_follower_band'] = in_array(($in['facebook_follower_band'] ?? ''), ['micro','small','medium','large'], true) ? $in['facebook_follower_band'] : 'micro';
        // facebook_has_cta_button (bool)
        $out['facebook_has_cta_button'] = isset($in['facebook_has_cta_button']) ? (bool)$in['facebook_has_cta_button'] : null;
        // has_instagram (bool)
        $out['has_instagram'] = (bool)($in['has_instagram'] ?? false);
        // instagram_activity (enum)
        $out['instagram_activity'] = in_array(($in['instagram_activity'] ?? ''), ['none','dormant','active'], true) ? $in['instagram_activity'] : 'none';
        // instagram_is_business (bool)
        $out['instagram_is_business'] = isset($in['instagram_is_business']) ? (bool)$in['instagram_is_business'] : null;
        // instagram_follower_band (enum)
        $out['instagram_follower_band'] = in_array(($in['instagram_follower_band'] ?? ''), ['micro','small','medium','large'], true) ? $in['instagram_follower_band'] : 'micro';
        // instagram_last_post_months (int)
        $out['instagram_last_post_months'] = isset($in['instagram_last_post_months']) && $in['instagram_last_post_months'] !== '' ? ((int)$in['instagram_last_post_months']) : null;
        // has_yelp (bool)
        $out['has_yelp'] = (bool)($in['has_yelp'] ?? false);
        // yelp_claimed (bool)
        $out['yelp_claimed'] = isset($in['yelp_claimed']) ? (bool)$in['yelp_claimed'] : null;
        // yelp_review_count (int)
        $out['yelp_review_count'] = isset($in['yelp_review_count']) && $in['yelp_review_count'] !== '' ? ((int)$in['yelp_review_count']) : null;
        // yelp_rating (decimal)
        $out['yelp_rating'] = isset($in['yelp_rating']) && $in['yelp_rating'] !== '' ? min(5.0, max(0.0, (float)$in['yelp_rating'])) : null;
        // has_angi (bool)
        $out['has_angi'] = (bool)($in['has_angi'] ?? false);
        // has_thumbtack (bool)
        $out['has_thumbtack'] = (bool)($in['has_thumbtack'] ?? false);
        // has_youtube (bool)
        $out['has_youtube'] = (bool)($in['has_youtube'] ?? false);
        // has_nextdoor_listing (bool)
        $out['has_nextdoor_listing'] = (bool)($in['has_nextdoor_listing'] ?? false);
        // has_bbb_listing (bool)
        $out['has_bbb_listing'] = (bool)($in['has_bbb_listing'] ?? false);
        // logo_quality (enum)
        $out['logo_quality'] = in_array(($in['logo_quality'] ?? ''), ['none','basic','professional'], true) ? $in['logo_quality'] : 'none';
        // has_before_after_photos (bool)
        $out['has_before_after_photos'] = (bool)($in['has_before_after_photos'] ?? false);
        // has_professional_email (bool)
        $out['has_professional_email'] = (bool)($in['has_professional_email'] ?? false);
        // is_licensed_insured_visible (bool)
        $out['is_licensed_insured_visible'] = (bool)($in['is_licensed_insured_visible'] ?? false);
        // has_service_guarantee (bool)
        $out['has_service_guarantee'] = (bool)($in['has_service_guarantee'] ?? false);
        // services_list (json_array)
        $out['services_list'] = json_encode(array_values(array_filter((array)($in['services_list'] ?? []), 'is_string')), JSON_UNESCAPED_SLASHES);
        // service_area_text (string)
        $out['service_area_text'] = mb_substr(trim((string)($in['service_area_text'] ?? '')), 0, 500);
        // booking_method (enum)
        $out['booking_method'] = in_array(($in['booking_method'] ?? ''), ['phone','facebook','email','form','app','unknown'], true) ? $in['booking_method'] : 'phone';
        // years_in_business (int)
        $out['years_in_business'] = isset($in['years_in_business']) && $in['years_in_business'] !== '' ? ((int)$in['years_in_business']) : null;
        // owner_age_band (enum)
        $out['owner_age_band'] = in_array(($in['owner_age_band'] ?? ''), ['unknown','under35','35-55','55plus'], true) ? $in['owner_age_band'] : 'unknown';
        // target_customer_type (enum)
        $out['target_customer_type'] = in_array(($in['target_customer_type'] ?? ''), ['unknown','residential','commercial','both'], true) ? $in['target_customer_type'] : 'unknown';
        // is_franchise (bool)
        $out['is_franchise'] = (bool)($in['is_franchise'] ?? false);
        // competitor_has_website (bool)
        $out['competitor_has_website'] = (bool)($in['competitor_has_website'] ?? false);
        // competitor_name (string)
        $out['competitor_name'] = mb_substr(trim((string)($in['competitor_name'] ?? '')), 0, 255);
        // competitor_website (string)
        $out['competitor_website'] = mb_substr(trim((string)($in['competitor_website'] ?? '')), 0, 255);
        // competitor_google_rating (decimal)
        $out['competitor_google_rating'] = isset($in['competitor_google_rating']) && $in['competitor_google_rating'] !== '' ? min(5.0, max(0.0, (float)$in['competitor_google_rating'])) : null;
        // competitor_review_count (int)
        $out['competitor_review_count'] = isset($in['competitor_review_count']) && $in['competitor_review_count'] !== '' ? ((int)$in['competitor_review_count']) : null;
        // opportunity_summary (text)
        $out['opportunity_summary'] = mb_substr(trim((string)($in['opportunity_summary'] ?? '')), 0, 1000);
        // strengths (json_array)
        $out['strengths'] = json_encode(array_values(array_filter((array)($in['strengths'] ?? []), 'is_string')), JSON_UNESCAPED_SLASHES);
        // gaps (json_array)
        $out['gaps'] = json_encode(array_values(array_filter((array)($in['gaps'] ?? []), 'is_string')), JSON_UNESCAPED_SLASHES);
        // recommended_package (enum)
        $out['recommended_package'] = in_array(($in['recommended_package'] ?? ''), ['standard','managed'], true) ? $in['recommended_package'] : 'standard';
        return [$out, $reject];
    }

    /** @return string[] every schema field name, in order */
    public const FIELDS = ['has_website','website_quality','website_notes','website_confidence','has_contact_form','has_online_booking','has_photo_gallery','has_about_page','has_faq_page','has_pricing_page','has_video_on_site','has_online_payment','site_appears_outdated','has_blog','has_testimonials_section','has_live_chat','mobile_friendly','has_ssl','has_google_business','google_review_count','google_rating','google_notes','has_gbp_posts','gbp_services_listed','gbp_hours_listed','gbp_photo_count','responds_to_reviews','last_review_date','review_quote_1','review_quote_1_author','review_quote_1_date','review_quote_2','review_quote_2_author','review_quote_2_date','has_facebook','facebook_activity','facebook_notes','facebook_page_type','facebook_last_post_months','facebook_follower_band','facebook_has_cta_button','has_instagram','instagram_activity','instagram_is_business','instagram_follower_band','instagram_last_post_months','has_yelp','yelp_claimed','yelp_review_count','yelp_rating','has_angi','has_thumbtack','has_youtube','has_nextdoor_listing','has_bbb_listing','logo_quality','has_before_after_photos','has_professional_email','is_licensed_insured_visible','has_service_guarantee','services_list','service_area_text','booking_method','years_in_business','owner_age_band','target_customer_type','is_franchise','competitor_has_website','competitor_name','competitor_website','competitor_google_rating','competitor_review_count','opportunity_summary','strengths','gaps','recommended_package'];
}
