<?php
error_reporting(E_ALL);ini_set('display_errors',isset($_GET['debug'])?'1':'0');session_start();
function h($s){return htmlspecialchars((string)$s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function has($s,$n){return strpos((string)$s,(string)$n)!==false;}
function m($t){if(!preg_match('/^(\d{1,2}):(\d{2})/',(string)$t,$x))return 0;return((int)$x[1]*60)+(int)$x[2];}
function nt($x){$x=(($x%1440)+1440)%1440;$h=(int)floor($x/60);$ap=$h>=12?'PM':'AM';$hh=$h%12;if(!$hh)$hh=12;return$hh.':'.sprintf('%02d',$x%60).$ap;}
function team($r){$x=strtolower(($r['team']??'').' '.($r['role_type']??''));if(has($x,'invest'))return'Investigator';if(has($x,'lead')||has($x,'tl'))return'Team Lead';if(has($x,'ops')||has($x,'operation'))return'Ops';return'Services';}
function db(){static$p=null;if($p)return$p;foreach(array(__DIR__.'/../../database.php',__DIR__.'/../database.php')as$f){if(is_file($f)){require_once$f;break;}}if(function_exists('ho_db'))$p=ho_db();elseif(isset($GLOBALS['pdo'])&&$GLOBALS['pdo']instanceof PDO)$p=$GLOBALS['pdo'];else throw new Exception('No DB connection found.');$p->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$p->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);return$p;}
function qv($p,$k,$d=null){try{$s=$p->prepare('SELECT v FROM wmt_settings WHERE k=?');$s->execute(array($k));$v=$s->fetchColumn();return$v===false?$d:$v;}catch(Exception$e){return$d;}}
function setup($p){
$p->exec("CREATE TABLE IF NOT EXISTS wmt_assignment_items(id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(80) NOT NULL UNIQUE,name VARCHAR(180) NOT NULL,scope VARCHAR(20) NOT NULL DEFAULT 'both',category VARCHAR(80) NOT NULL DEFAULT 'Task',priority VARCHAR(20) NOT NULL DEFAULT 'Medium',estimated_minutes INT NOT NULL DEFAULT 10,preferred_role VARCHAR(30) NOT NULL DEFAULT 'door_owner',active TINYINT(1) NOT NULL DEFAULT 1,instructions TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$p->exec("CREATE TABLE IF NOT EXISTS wmt_auto_assignments(id INT AUTO_INCREMENT PRIMARY KEY,work_date DATE NOT NULL,assignment_type VARCHAR(50) NOT NULL,side VARCHAR(20),associate_name VARCHAR(120),start_time TIME NULL,end_time TIME NULL,item_code VARCHAR(80),item_name VARCHAR(180),target_associate VARCHAR(120),status VARCHAR(30) NOT NULL DEFAULT 'Assigned',source VARCHAR(40) NOT NULL DEFAULT 'auto',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY d(work_date),KEY assoc(associate_name),KEY item(item_code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
seed_items($p);
}
function seed_items($p){$items=array(
array('SIDE_VESTIBULE','Vestibule clean and clear of spills/trash','both','Safety','Critical',10,'door_owner','Complete for assigned side. Keep path clear; report anything that cannot be corrected immediately.'),
array('SIDE_CART_WIPES','Cart wipes dispenser cleaned/stocked','both','Entrance Readiness','High',8,'door_owner','Check and clean the dispenser area for assigned side.'),
array('SIDE_BENCHES','Benches cleaned','both','Entrance Readiness','Medium',8,'door_owner','Clean benches on assigned side.'),
array('SIDE_WINDOWS','Windows cleaned','both','Entrance Readiness','High',15,'door_owner','Clean visible customer-facing windows on assigned side.'),
array('SIDE_DOORS','Doors cleaned','both','Entrance Readiness','High',15,'door_owner','Clean handles/glass/visible smudges on assigned side.'),
array('SIDE_TRACK','Door track swept','both','Entrance Readiness','Medium',10,'door_owner','Sweep door track on assigned side when traffic allows.'),
array('SIDE_EAS','Dust EAS pedestals','both','Entrance Readiness','Medium',8,'door_owner','Dust EAS pedestals on assigned side.'),
array('SIDE_MART_CARTS','Bottom of Mart Carts wiped','both','Entrance Readiness','High',20,'floater','Complete for assigned side. Floater preferred; door owner only when coverage allows.'),
array('SIDE_PROTECTION_DEVICES','Protection devices returned/organized check','both','Merchandise Protection','Medium',10,'door_owner','Organize/return protection devices for assigned side as applicable.'),
array('SIDE_EQUIPMENT','Door/vestibule equipment issue check','both','Safety','Medium',6,'door_owner','Check for door, mat, cone, cart wipe, or equipment issues on assigned side.'),
array('GEN_GO_BACKS','Go backs / front-end returns support','general','Front End Support','Medium',20,'floater','Floater task only after doors, breaks, and lunches are protected.'),
array('GEN_CLOSETS','Closets NCO','general','Organization','Low',15,'floater','Keep AP/vestibule storage neat, clean, and organized.'),
array('GEN_HANDOFF','AP Services handoff note','general','Communication','Medium',8,'floater','Document open issues, missed tasks, weather/safety concerns, and coverage gaps.'),
array('TRG_WEATHER','Inclement weather vestibule response','triggered','Safety','Critical',20,'floater','Triggered task. Mats/cones/residual water response overrides lower-priority tasks.'),
array('TRG_SUSPICIOUS','Suspicious activity report/escalation','triggered','Reporting','High',5,'door_owner','Triggered task. Observe/report only; do not investigate or detain.')
);$q=$p->prepare('INSERT IGNORE INTO wmt_assignment_items(code,name,scope,category,priority,estimated_minutes,preferred_role,instructions) VALUES(?,?,?,?,?,?,?,?)');foreach($items as$i)$q->execute($i);}
function auth($p){$hash=qv($p,'admin_hash');if(!$hash){header('Location:index.php');exit;}if(($_POST['form']??'')==='login'&&password_verify($_POST['password']??'',$hash)){$_SESSION['wmt']=1;header('Location:assignments.php');exit;}if(empty($_SESSION['wmt'])){echo'<!doctype html><title>Login</title><link rel="stylesheet" href="walmart-theme.css"><div class="card" style="max-width:420px;margin:12vh auto"><h1>AP Services Login</h1><form method="post"><input type="hidden" name="form" value="login"><input type="password" name="password" placeholder="Password"><button>Continue</button></form></div>';exit;}}
function shifts($p,$d){$q=$p->prepare('SELECT s.*,a.preferred_door,a.can_cover,a.reliability FROM wmt_shifts s LEFT JOIN wmt_associates a ON a.id=s.associate_id WHERE work_date=? ORDER BY start_time,associate_name');$q->execute(array($d));return$q->fetchAll();}
function span($s){$st=m(substr($s['start_time'],0,5));$en=m(substr($s['end_time'],0,5));if($en<=$st)$en+=1440;return array($st,$en,$en-$st);}
function covers($s,$a,$b){$x=span($s);return$a>=$x[0]&&$b<=$x[1];}
function breaks($s,$slot){$x=span($s);$st=$x[0];$en=$x[1];$dur=$x[2];$out=array();if($dur>=480){$q=$dur/4;$out[]=array('Break 1',(int)(round(($st+$q-8)/$slot)*$slot),15);$out[]=array('Lunch',(int)(round(($st+2*$q-30)/$slot)*$slot),60);$out[]=array('Break 2',(int)(round(($st+3*$q-8)/$slot)*$slot),15);}elseif($dur>=360){$out[]=array('Break',(int)(round(($st+$dur/3-8)/$slot)*$slot),15);$out[]=array('Lunch',(int)(round(($st+$dur*2/3-15)/$slot)*$slot),30);}elseif($dur>=240){$out[]=array('Break',(int)(round(($st+$dur/2-8)/$slot)*$slot),15);}return$out;}
function off($s,$t,$slot){foreach(breaks($s,$slot)as$b){if($t>=$b[1]&&$t<$b[1]+$b[2])return$b[0];}return'';}
function hist($p,$d){$out=array();try{$q=$p->prepare('SELECT associate_name,assignment_type,side,item_code,COUNT(*) c,SUM(TIMESTAMPDIFF(MINUTE,start_time,end_time)) mins FROM wmt_auto_assignments WHERE work_date<? AND associate_name IS NOT NULL GROUP BY associate_name,assignment_type,side,item_code');$q->execute(array($d));foreach($q->fetchAll()as$r){$n=$r['associate_name'];$out[$n]['total']=($out[$n]['total']??0)+(int)$r['c'];if($r['side'])$out[$n]['side_'.$r['side']]=($out[$n]['side_'.$r['side']]??0)+(int)$r['c'];if($r['item_code'])$out[$n]['item_'.$r['item_code']]=($out[$n]['item_'.$r['item_code']]??0)+(int)$r['c'];$out[$n]['minutes']=($out[$n]['minutes']??0)+(int)$r['mins'];}}catch(Exception$e){}return$out;}
function score_person($n,$side,$pref,$hist,$dayMin,$weekLoad){$s=0;$s+=($dayMin[$n][$side]??0)/15;$s+=($hist[$n]['side_'.$side]??0)*3;$s+=($hist[$n]['minutes']??0)/180;$s+=($weekLoad[$n]??0)/60;if($pref===$side)$s-=8;elseif($pref==='Either')$s-=2;return$s;}
function pick_service($c,$side,$used,$hist,$dayMin,$weekLoad){$best=null;$bs=999999;foreach($c as$r){$n=$r['associate_name'];if(isset($used[$n]))continue;$s=score_person($n,$side,$r['preferred_door']??'Either',$hist,$dayMin,$weekLoad)-((float)($r['reliability']??3));if($s<$bs){$bs=$s;$best=$r;}}return$best;}
function build_plan($p,$d){$sh=shifts($p,$d);$slot=(int)qv($p,'slot_minutes',15);if($slot<5)$slot=15;$start=m(qv($p,'triage_start','08:00'));$end=m(qv($p,'triage_end','17:00'));$opsB=m(qv($p,'ops_blackout_start','10:00'));$opsE=m(qv($p,'ops_blackout_end','12:00'));$opsMax=(int)qv($p,'ops_flex_per_person',30);$tlMax=(int)qv($p,'tl_flex_per_day',15);$hist=hist($p,$d);$rows=array();$dayMin=array();$weekLoad=array();$opsUsed=array();$tlUsed=0;$sideMin=array('Grocery'=>array(),'GM'=>array());$floaterMin=array();for($t=$start;$t<$end;$t+=$slot){$avail=array();$off=array();foreach($sh as$s){if(!covers($s,$t,$t+$slot))continue;$o=off($s,$t,$slot);if($o)$off[]=array('name'=>$s['associate_name'],'label'=>$o);else$avail[]=$s;}$svc=array();$ops=array();$tls=array();foreach($avail as$x){$tm=team($x);if($tm==='Services'&&(int)($x['can_cover']??1))$svc[]=$x;elseif($tm==='Ops')$ops[]=$x;elseif($tm==='Team Lead')$tls[]=$x;}$used=array();$g=pick_service($svc,'Grocery',$used,$hist,$dayMin,$weekLoad);if($g){$n=$g['associate_name'];$used[$n]=1;$dayMin[$n]['Grocery']=($dayMin[$n]['Grocery']??0)+$slot;$sideMin['Grocery'][$n]=($sideMin['Grocery'][$n]??0)+$slot;}$gm=pick_service($svc,'GM',$used,$hist,$dayMin,$weekLoad);if($gm){$n=$gm['associate_name'];$used[$n]=1;$dayMin[$n]['GM']=($dayMin[$n]['GM']??0)+$slot;$sideMin['GM'][$n]=($sideMin['GM'][$n]??0)+$slot;}$flex=array();foreach(array('Grocery','GM')as$side){$covered=$side==='Grocery'?$g:$gm;if($covered)continue;$assigned=null;if(count($ops)>=2&&!($t<$opsE&&$t+$slot>$opsB)){foreach($ops as$o){$n=$o['associate_name'];if(!isset($used[$n])&&(($opsUsed[$n]??0)+$slot)<=$opsMax){$assigned=$o;$used[$n]=1;$opsUsed[$n]=($opsUsed[$n]??0)+$slot;$flex[]=$n.' Ops flex';break;}}}if(!$assigned&&$tlUsed+$slot<=$tlMax&&$tls){foreach($tls as$tl){$n=$tl['associate_name'];if(!isset($used[$n])){$assigned=$tl;$used[$n]=1;$tlUsed+=$slot;$flex[]=$n.' TL flex';break;}}}if($assigned){if($side==='Grocery')$g=$assigned;else$gm=$assigned;}}$fl='';foreach($svc as$s){$n=$s['associate_name'];if(!isset($used[$n])){$fl=$n;$floaterMin[$n]=($floaterMin[$n]??0)+$slot;break;}}$rows[]=array('start'=>$t,'end'=>$t+$slot,'Grocery'=>$g?$g['associate_name']:'','GM'=>$gm?$gm['associate_name']:'','floater'=>$fl,'off'=>$off,'flex'=>implode(', ',$flex));}return array('rows'=>$rows,'side_minutes'=>$sideMin,'floater_minutes'=>$floaterMin,'shifts'=>$sh,'hist'=>$hist);}
function blocks($rows,$field,$name){$b=array();foreach($rows as$r){if(($r[$field]??'')!==$name)continue;$i=count($b)-1;if($i>=0&&$b[$i]['end']===$r['start'])$b[$i]['end']=$r['end'];else$b[]=array('start'=>$r['start'],'end'=>$r['end']);}return$b;}
function add(&$a,$type,$side,$name,$st,$en,$code,$item,$target,$notes){$a[]=array('assignment_type'=>$type,'side'=>$side,'associate_name'=>$name,'start'=>$st,'end'=>$en,'item_code'=>$code,'item_name'=>$item,'target_associate'=>$target,'notes'=>$notes);}
function items($p){$rows=$p->query("SELECT * FROM wmt_assignment_items WHERE active=1 ORDER BY FIELD(priority,'Critical','High','Medium','Low'),estimated_minutes DESC,name")->fetchAll();return$rows;}
function task_score($n,$item,$side,$owners,$floats,$hist,$load){$s=($load[$n]??0)/10+($hist[$n]['item_'.$item['code']]??0)*5+($hist[$n]['total']??0);$s-=($owners[$n]??0)/90;$s-=($floats[$n]??0)/45;if($item['preferred_role']==='floater')$s-=($floats[$n]??0)/30;return$s;}
function choose_task_owner($item,$side,$pl,&$load){$hist=$pl['hist'];$owners=$side?$pl['side_minutes'][$side]:array();$floats=$pl['floater_minutes'];$pool=array();if($item['preferred_role']==='floater'&&$floats)$pool=array_keys($floats);if(!$pool&&$owners)$pool=array_keys($owners);if(!$pool&&$floats)$pool=array_keys($floats);if(!$pool)return'Unassigned';$best='Unassigned';$bs=999999;foreach($pool as$n){$s=task_score($n,$item,$side,$owners,$floats,$hist,$load);if($s<$bs){$bs=$s;$best=$n;}}$load[$best]=($load[$best]??0)+(int)$item['estimated_minutes'];return$best;}
function window_for($pl,$side,$n){if($n==='Unassigned')return array(null,null,'No owner/floater available');if($side){$b=blocks($pl['rows'],$side,$n);if($b)return array($b[0]['start'],$b[0]['end'],nt($b[0]['start']).'-'.nt($b[0]['end']));}$b=blocks($pl['rows'],'floater',$n);if($b)return array($b[0]['start'],$b[0]['end'],nt($b[0]['start']).'-'.nt($b[0]['end']));return array(null,null,'During assigned coverage when traffic allows');}
function generate($p,$d){$pl=build_plan($p,$d);$out=array();$load=array();foreach(array('Grocery','GM')as$side){$names=array_keys($pl['side_minutes'][$side]);foreach($names as$n){foreach(blocks($pl['rows'],$side,$n)as$b)add($out,'Door Post',$side,$n,$b['start'],$b['end'],null,$side.' Door',null,'Primary post assignment generated from schedule.');}}foreach($pl['floater_minutes']as$n=>$min){foreach(blocks($pl['rows'],'floater',$n)as$b)add($out,'Floater / Break Cover','Both',$n,$b['start'],$b['end'],null,'Floater / Break Cover',null,'Stay available for break/lunch relief first; complete general tasks only when doors are protected.');}foreach($pl['rows']as$r){foreach($r['off']as$o)add($out,'Break/Lunch',null,$o['name'],$r['start'],$r['end'],null,$o['label'],null,'Scheduled '.$o['label'].'. Do not leave until relieved if posted.');}
foreach(items($p)as$item){if($item['scope']==='triggered')continue;if($item['scope']==='both'){foreach(array('Grocery','GM')as$side){$n=choose_task_owner($item,$side,$pl,$load);$w=window_for($pl,$side,$n);add($out,'Door Task',$side,$n,$w[0],$w[1],$item['code'],$item['name'],null,$item['instructions'].' Suggested: '.$w[2]);}}elseif($item['scope']==='general'){$n=choose_task_owner($item,null,$pl,$load);$w=window_for($pl,null,$n);add($out,'General Task','Both',$n,$w[0],$w[1],$item['code'],$item['name'],null,$item['instructions'].' Suggested: '.$w[2]);}}
return array($out,$pl);}
function save_day($p,$d,$rows){$p->prepare('DELETE FROM wmt_auto_assignments WHERE work_date=?')->execute(array($d));$q=$p->prepare('INSERT INTO wmt_auto_assignments(work_date,assignment_type,side,associate_name,start_time,end_time,item_code,item_name,target_associate,notes) VALUES(?,?,?,?,?,?,?,?,?,?)');foreach($rows as$r){$st=$r['start']===null?null:sprintf('%02d:%02d:00',floor($r['start']/60)%24,$r['start']%60);$en=$r['end']===null?null:sprintf('%02d:%02d:00',floor($r['end']/60)%24,$r['end']%60);$q->execute(array($d,$r['assignment_type'],$r['side'],$r['associate_name'],$st,$en,$r['item_code'],$r['item_name'],$r['target_associate'],$r['notes']));}return count($rows);}
function add_item($p){$name=trim($_POST['name']??'');if(!$name)return'No task name entered.';$code='CUSTOM_'.strtoupper(preg_replace('/[^A-Z0-9]+/','_',substr($name,0,50))).'_'.date('His');$scope=$_POST['scope']??'general';if(!in_array($scope,array('both','general','triggered'))) $scope='general';$p->prepare('INSERT INTO wmt_assignment_items(code,name,scope,category,priority,estimated_minutes,preferred_role,instructions) VALUES(?,?,?,?,?,?,?,?)')->execute(array($code,$name,$scope,$_POST['category']??'Custom',$_POST['priority']??'Medium',(int)($_POST['estimated_minutes']??10),$_POST['preferred_role']??'floater',$_POST['instructions']??''));return'Added task definition: '.$name;}
function headp($t){echo'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.h($t).'</title><link rel="stylesheet" href="walmart-theme.css"><div class="top no-print"><div class="wrap"><b>AP Services Tool</b><div class="nav"><a href="index.php">Dashboard</a><a href="assignments.php">Assignments</a><a href="tasks.php">Door Tasks</a><a href="index.php?v=week">Week</a><a href="index.php?v=turnin">Turn-In</a></div></div></div><main class="wrap">';}
function foot(){echo'</main>';}
try{$p=db();setup($p);auth($p);$d=$_GET['date']??date('Y-m-d');$msg='';if($_SERVER['REQUEST_METHOD']==='POST'){if(($_POST['form']??'')==='add_item')$msg=add_item($p);}$gen=generate($p,$d);$rows=$gen[0];$pl=$gen[1];if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['form']??'')==='save')$msg='Saved '.save_day($p,$d,$rows).' assignments for '.$d.'.';headp('Daily Assignments');if($msg)echo'<div class="card"><b>'.h($msg).'</b></div>';echo'<div class="card no-print"><form><input type="date" name="date" value="'.h($d).'"><button>Load</button></form><form method="post"><input type="hidden" name="form" value="save"><button>Generate and save today</button></form></div>';echo'<div class="card"><h1 class="print-title">Automatic Daily Assignment Plan - '.h($d).'</h1><p class="muted">This generates full daily ownership: door posts, break/lunch coverage, floater/break cover, side-specific tasks for Grocery and GM, and general tasks like go-backs. Assignment choices use today\'s schedule plus saved historical assignments to spread work over time.</p></div>';
$by=array();foreach($rows as$r){$by[$r['associate_name']?:'Unassigned'][]=$r;}ksort($by);foreach($by as$n=>$list){echo'<div class="card"><h2>'.h($n).'</h2><table><tr><th>Type</th><th>Side</th><th>Time</th><th>Assignment</th><th>Notes</th></tr>';foreach($list as$r){$time=$r['start']===null?'As able':nt($r['start']).'-'.nt($r['end']);echo'<tr><td>'.h($r['assignment_type']).'</td><td>'.h($r['side']?:'-').'</td><td>'.h($time).'</td><td><b>'.h($r['item_name']).'</b></td><td>'.h($r['notes']).'</td></tr>';}echo'</table></div>';}
echo'<div class="card"><h2>Task definitions</h2><table><tr><th>Code</th><th>Name</th><th>Scope</th><th>Priority</th><th>Minutes</th><th>Preferred Role</th></tr>';foreach(items($p)as$i)echo'<tr><td>'.h($i['code']).'</td><td>'.h($i['name']).'</td><td>'.h($i['scope']).'</td><td>'.h($i['priority']).'</td><td>'.h($i['estimated_minutes']).'</td><td>'.h($i['preferred_role']).'</td></tr>';echo'</table></div>';
echo'<div class="card no-print"><h2>Add a new task definition</h2><form method="post"><input type="hidden" name="form" value="add_item"><p><input name="name" placeholder="Task name, e.g. Go backs from Service Desk"></p><p><select name="scope"><option value="both">Both doors / side task</option><option value="general">General floater task</option><option value="triggered">Triggered only</option></select></p><p><select name="priority"><option>Medium</option><option>Critical</option><option>High</option><option>Low</option></select></p><p><input name="estimated_minutes" type="number" value="10"> minutes</p><p><select name="preferred_role"><option value="door_owner">Door owner</option><option value="floater">Floater</option><option value="any">Any AP Service TA</option></select></p><p><textarea name="instructions" placeholder="Instructions"></textarea></p><button>Add task</button></form></div>';foot();}catch(Throwable$e){http_response_code(500);headp('Assignment error');echo'<div class="card"><h1>Assignment setup error</h1><pre>'.h($e->getMessage()).'</pre></div>';foot();}
