<?php
error_reporting(E_ALL);
ini_set('display_errors', isset($_GET['debug']) ? '1' : '0');
ini_set('log_errors', '1');
session_start();

function wmt_h($s){ return htmlspecialchars((string)$s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function wmt_has($a,$b){ return strpos((string)$a,(string)$b) !== false; }
function wmt_min($t){ if(!preg_match('/^(\d{1,2}):(\d{2})/',(string)$t,$m)) return 0; return ((int)$m[1]*60)+(int)$m[2]; }
function wmt_nice($m){ $m=(($m%1440)+1440)%1440; $h=intdiv($m,60); $ap=$h>=12?'PM':'AM'; $hh=$h%12; if(!$hh)$hh=12; return $hh.':'.sprintf('%02d',$m%60).$ap; }
function wmt_team($r){ $x=strtolower(($r['team']??'').' '.($r['role_type']??'')); if(wmt_has($x,'invest')) return 'Investigator'; if(wmt_has($x,'lead')||wmt_has($x,'tl')) return 'Team Lead'; if(wmt_has($x,'ops')) return 'Ops'; return 'Services'; }

function wmt_db(){
  static $pdo=null; if($pdo) return $pdo;
  foreach(array(__DIR__.'/../../database.php', __DIR__.'/../database.php') as $f){ if(is_file($f)){ require_once $f; break; } }
  if(function_exists('ho_db')) $pdo=ho_db();
  elseif(isset($GLOBALS['pdo']) && $GLOBALS['pdo'] instanceof PDO) $pdo=$GLOBALS['pdo'];
  else throw new Exception('No database connection found. Expected database.php with ho_db().');
  $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
  $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
  return $pdo;
}
function wmt_schema($pdo){
  $pdo->exec('CREATE TABLE IF NOT EXISTS wmt_settings (k VARCHAR(80) PRIMARY KEY, v LONGTEXT, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
  $pdo->exec('CREATE TABLE IF NOT EXISTS wmt_associates (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, team VARCHAR(40) NOT NULL DEFAULT \'Services\', role_type VARCHAR(80) NOT NULL DEFAULT \'AP Service TA\', can_cover TINYINT(1) NOT NULL DEFAULT 1, preferred_door VARCHAR(20) NOT NULL DEFAULT \'Either\', active TINYINT(1) NOT NULL DEFAULT 1, reliability DECIMAL(5,2) NOT NULL DEFAULT 3.00, notes TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
  $pdo->exec('CREATE TABLE IF NOT EXISTS wmt_shifts (id INT AUTO_INCREMENT PRIMARY KEY, work_date DATE NOT NULL, associate_id INT NULL, associate_name VARCHAR(120) NOT NULL, team VARCHAR(40) NOT NULL DEFAULT \'Services\', role_type VARCHAR(80) NOT NULL DEFAULT \'AP Service TA\', start_time TIME NOT NULL, end_time TIME NOT NULL, notes TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, KEY work_date (work_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
  $pdo->exec('CREATE TABLE IF NOT EXISTS wmt_tasks (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180) NOT NULL UNIQUE, category VARCHAR(60) NOT NULL DEFAULT \'Entrance Readiness\', priority VARCHAR(20) NOT NULL DEFAULT \'Medium\', weight INT NOT NULL DEFAULT 2, frequency VARCHAR(40) NOT NULL DEFAULT \'Daily\', active TINYINT(1) NOT NULL DEFAULT 1, notes TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
  $pdo->exec('CREATE TABLE IF NOT EXISTS wmt_turnins (id INT AUTO_INCREMENT PRIMARY KEY, work_date DATE NOT NULL, task_name VARCHAR(180) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT \'Not Started\', completed_by VARCHAR(120), notes TEXT, manager_signoff VARCHAR(120), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, KEY work_date (work_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
  $pdo->exec('CREATE TABLE IF NOT EXISTS wmt_exceptions (id INT AUTO_INCREMENT PRIMARY KEY, work_date DATE NOT NULL, type VARCHAR(80) NOT NULL, post VARCHAR(20), start_time TIME, end_time TIME, associate_name VARCHAR(120), severity VARCHAR(20) NOT NULL DEFAULT \'Medium\', notes TEXT, reported_to VARCHAR(120), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, KEY work_date (work_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
  wmt_seed($pdo);
}
function wmt_get($pdo,$k,$d=null){ $s=$pdo->prepare('SELECT v FROM wmt_settings WHERE k=?'); $s->execute(array($k)); $v=$s->fetchColumn(); return $v===false?$d:$v; }
function wmt_set($pdo,$k,$v){ $pdo->prepare('INSERT INTO wmt_settings(k,v) VALUES(?,?) ON DUPLICATE KEY UPDATE v=VALUES(v)')->execute(array($k,$v)); }
function wmt_seed($pdo){
  foreach(array('triage_start'=>'08:00','triage_end'=>'17:00','ops_blackout_start'=>'10:00','ops_blackout_end'=>'12:00','ops_flex_per_person'=>'30','tl_flex_per_day'=>'15') as $k=>$v){ if(wmt_get($pdo,$k)===null) wmt_set($pdo,$k,$v); }
  $tasks=array('Dust EAS pedestals','Cart wipes dispenser cleaned','Benches cleaned','Windows cleaned','Doors cleaned','Door track swept','Closets NCO','Bottom of Mart Carts wiped','Vestibules clean and clear of spills/trash','Inclement weather response','Front entrance safety/security observation','Greet, help, and thank customers','Visual theft deterrence','Merchandise protection device support','Suspicious activity report/escalation');
  $q=$pdo->prepare('INSERT IGNORE INTO wmt_tasks(name) VALUES(?)'); foreach($tasks as $t) $q->execute(array($t));
}
function wmt_login($title,$form){ echo '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.wmt_h($title).'</title><body style="font-family:system-ui;background:#f4f1ea"><div style="max-width:420px;margin:12vh auto;background:white;padding:28px;border-radius:18px;border:1px solid #ddd"><h1>'.wmt_h($title).'</h1><form method="post"><input type="hidden" name="form" value="'.wmt_h($form).'"><input type="password" name="password" placeholder="Password" required style="width:100%;padding:12px"><button style="width:100%;padding:12px;margin-top:10px;background:#223b2a;color:white;font-weight:800">Continue</button></form></div>'; exit; }
function wmt_auth($pdo){ $hash=wmt_get($pdo,'admin_hash'); if(!$hash){ if(($_POST['form']??'')==='setpass' && strlen($_POST['password']??'')>=8){ wmt_set($pdo,'admin_hash',password_hash($_POST['password'],PASSWORD_DEFAULT)); $_SESSION['wmt']=1; header('Location:index.php'); exit; } wmt_login('Create WMT Admin Password','setpass'); } if(isset($_GET['logout'])){ unset($_SESSION['wmt']); header('Location:index.php'); exit; } if(($_POST['form']??'')==='login' && password_verify($_POST['password']??'',$hash)){ $_SESSION['wmt']=1; header('Location:index.php'); exit; } if(empty($_SESSION['wmt'])) wmt_login('AP Services Login','login'); }
function wmt_breaks($s){ $st=wmt_min(substr($s['start_time'],0,5)); $en=wmt_min(substr($s['end_time'],0,5)); if($en<=$st)$en+=1440; $dur=$en-$st; $out=array(); if($dur>=480){ $q=$dur/4; $out[]=array('Break 1',round(($st+$q-8)/15)*15,15); $out[]=array('Lunch',round(($st+2*$q-30)/15)*15,60); $out[]=array('Break 2',round(($st+3*$q-8)/15)*15,15); } elseif($dur>=360){ $out[]=array('Break',round(($st+$dur/3-8)/15)*15,15); $out[]=array('Lunch',round(($st+$dur*2/3-15)/15)*15,30); } elseif($dur>=240){ $out[]=array('Break',round(($st+$dur/2-8)/15)*15,15); } return $out; }
function wmt_off($s,$a,$b){ foreach(wmt_breaks($s) as $x){ if($a<$x[1]+$x[2] && $b>$x[1]) return $x[0]; } return ''; }
function wmt_on($s,$a,$b){ $st=wmt_min(substr($s['start_time'],0,5)); $en=wmt_min(substr($s['end_time'],0,5)); if($en<=$st)$en+=1440; return $a>=$st && $b<=$en; }
function wmt_up_assoc($pdo,$r){ $n=trim($r['name']??$r['associate_name']??''); if(!$n)return 0; $team=$r['team']??'Services'; $role=$r['role_type']??'AP Service TA'; $pref=$r['preferred_door']??'Either'; if(!in_array($pref,array('Grocery','GM','Either'))) $pref='Either'; $can=wmt_team(array('team'=>$team,'role_type'=>$role))==='Investigator'?0:1; $pdo->prepare('INSERT INTO wmt_associates(name,team,role_type,can_cover,preferred_door,notes) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE team=VALUES(team),role_type=VALUES(role_type),can_cover=VALUES(can_cover),preferred_door=VALUES(preferred_door),notes=VALUES(notes)')->execute(array($n,$team,$role,$can,$pref,$r['notes']??null)); $id=(int)$pdo->lastInsertId(); if(!$id){$q=$pdo->prepare('SELECT id FROM wmt_associates WHERE name=?');$q->execute(array($n));$id=(int)$q->fetchColumn();} return $id; }
function wmt_import($pdo){ if($_SERVER['REQUEST_METHOD']!=='POST')return ''; $f=$_POST['form']??''; if($f==='json'){ $j=json_decode($_POST['payload']??'',true); if(!is_array($j))return 'Bad JSON'; foreach($j['replace_schedule_dates']??array() as $d)$pdo->prepare('DELETE FROM wmt_shifts WHERE work_date=?')->execute(array($d)); foreach($j['associates']??array() as $a)wmt_up_assoc($pdo,$a); $c=0; foreach($j['schedule']??array() as $s){ $d=$s['date']??$s['work_date']??''; $n=$s['name']??$s['associate_name']??''; $start=$s['start']??$s['start_time']??''; $end=$s['end']??$s['end_time']??''; if(!$d||!$n||!$start||!$end)continue; $id=wmt_up_assoc($pdo,array('name'=>$n,'team'=>$s['team']??'Services','role_type'=>$s['role_type']??'AP Service TA','preferred_door'=>$s['preferred_door']??'Either')); $pdo->prepare('INSERT INTO wmt_shifts(work_date,associate_id,associate_name,team,role_type,start_time,end_time,notes) VALUES(?,?,?,?,?,?,?,?)')->execute(array($d,$id,$n,$s['team']??'Services',$s['role_type']??'AP Service TA',$start,$end,$s['notes']??null)); $c++; } return 'Imported '.$c.' JSON schedule rows'; }
 if($f==='csv'){ $lines=preg_split('/\r\n|\n|\r/',trim($_POST['csv']??'')); $h=array_map('trim',str_getcsv(array_shift($lines))); $h=array_map('strtolower',$h); $c=0; foreach($lines as $line){ if(!trim($line))continue; $v=str_getcsv($line); $r=array(); foreach($h as $i=>$k)$r[$k]=$v[$i]??''; if(empty($r['date'])||empty($r['name'])||empty($r['start'])||empty($r['end']))continue; $id=wmt_up_assoc($pdo,$r); $pdo->prepare('INSERT INTO wmt_shifts(work_date,associate_id,associate_name,team,role_type,start_time,end_time,notes) VALUES(?,?,?,?,?,?,?,?)')->execute(array($r['date'],$id,$r['name'],$r['team']??'Services',$r['role_type']??'AP Service TA',$r['start'],$r['end'],$r['notes']??null)); $c++; } return 'Imported '.$c.' CSV rows'; }
 if($f==='turnin'){ foreach($_POST['task']??array() as $t)$pdo->prepare('INSERT INTO wmt_turnins(work_date,task_name,status,completed_by,notes,manager_signoff) VALUES(?,?,?,?,?,?)')->execute(array($_POST['date'],$t['name'],$t['status'],$t['by'],$t['notes'],$_POST['mgr']??null)); return 'Turn-in saved'; } return ''; }
function wmt_shifts($pdo,$d){ $q=$pdo->prepare('SELECT s.*,a.preferred_door,a.can_cover,a.reliability FROM wmt_shifts s LEFT JOIN wmt_associates a ON a.id=s.associate_id WHERE work_date=? ORDER BY start_time,associate_name'); $q->execute(array($d)); return $q->fetchAll(); }
function wmt_plan($pdo,$d){ $sh=wmt_shifts($pdo,$d); $rows=array(); $cnt=array(); $opsUsed=array(); $tlUsed=0; $gap=0; $cov=0; $req=0; $float=0; for($t=wmt_min('08:00');$t<wmt_min('17:00');$t+=15){ $u=array(); $off=array(); foreach($sh as $s){ if(wmt_on($s,$t,$t+15)){ $o=wmt_off($s,$t,$t+15); if($o)$off[]=$s['associate_name'].' '.$o; else $u[]=$s; } } $svc=array();$ops=array();$tl=array(); foreach($u as $x){ $team=wmt_team($x); if($team==='Services' && (int)($x['can_cover']??1))$svc[]=$x; elseif($team==='Ops')$ops[]=$x; elseif($team==='Team Lead')$tl[]=$x; } $used=array(); $g='';$gm=''; foreach($svc as $s){ if(!$g){$g=$s['associate_name'];$used[$g]=1;} elseif(!$gm && empty($used[$s['associate_name']])){$gm=$s['associate_name'];$used[$gm]=1;break;} } $flex=array(); foreach(array('Grocery','GM') as $door){ if(($door==='Grocery'&&$g)||($door==='GM'&&$gm))continue; $assigned=''; if(count($ops)>=2 && !($t<720&&$t+15>600)){ foreach($ops as $o){$n=$o['associate_name']; if(empty($used[$n]) && (($opsUsed[$n]??0)+15)<=30){$assigned=$n;$used[$n]=1;$opsUsed[$n]=($opsUsed[$n]??0)+15;$flex[]=$n.' Ops flex';break;}} } if(!$assigned && $tlUsed<15 && $tl){ foreach($tl as $x){$n=$x['associate_name']; if(empty($used[$n])){$assigned=$n;$used[$n]=1;$tlUsed+=15;$flex[]=$n.' TL flex';break;}} } if($assigned){ if($door==='Grocery')$g=$assigned; else $gm=$assigned; } }
 $fl=''; foreach($svc as $s){ if(empty($used[$s['associate_name']])){$fl=$s['associate_name'];$float+=15;break;} } $note=array(); $req+=30; if($g)$cov+=15; else{$gap+=15;$note[]='Grocery gap';} if($gm)$cov+=15; else{$gap+=15;$note[]='GM gap';} $rows[]=array($t,$t+15,$g,$gm,$fl,implode(', ',$off),implode(', ',$flex),implode('; ',$note)); } return array('date'=>$d,'shifts'=>$sh,'rows'=>$rows,'gap'=>$gap,'cov'=>$cov,'req'=>$req,'pct'=>$req?round($cov/$req*100,1):0,'float'=>$float); }
function wmt_head($t){ echo '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.wmt_h($t).'</title><style>body{margin:0;background:#f4f1ea;font-family:system-ui;color:#172019}.top{background:#223b2a;color:white}.wrap{max-width:1200px;margin:auto;padding:18px}.nav a{color:white;margin-right:14px;font-weight:800}.card{background:white;border:1px solid #ddd2bf;border-radius:16px;padding:16px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.kpi{background:#fff8ea;border:1px solid #ddd2bf;border-radius:12px;padding:12px}.kpi b{font-size:28px;display:block}.bad{color:#a32016;font-weight:900}.ok{color:#18632d;font-weight:900}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:7px;text-align:left;vertical-align:top}th{background:#f1eadc}textarea{width:100%;min-height:160px}button,.btn{background:#223b2a;color:white;padding:9px;border-radius:9px;font-weight:800;text-decoration:none}@media print{.top,.no-print{display:none}.card{border:0;margin:0 0 12px;padding:0}body{background:white;font-size:12px}}</style><div class="top no-print"><div class="wrap"><b>AP Services Tool</b><div class="nav"><a href="index.php">Dashboard</a><a href="?v=week">Week</a><a href="?v=import">Import</a><a href="?v=turnin">Turn-In</a><a href="?export=json">Export</a><a href="?logout=1">Logout</a></div></div></div><main class="wrap">'; }
function wmt_tables($pl){ echo '<div class="card"><h2>Who is here</h2><table><tr><th>Name</th><th>Team</th><th>Role</th><th>Shift</th><th>Break/Lunch</th></tr>'; foreach($pl['shifts'] as $s){$b=array();foreach(wmt_breaks($s) as $x)$b[]=$x[0].' '.wmt_nice($x[1]).'-'.wmt_nice($x[1]+$x[2]); echo '<tr><td><b>'.wmt_h($s['associate_name']).'</b></td><td>'.wmt_h($s['team']).'</td><td>'.wmt_h($s['role_type']).'</td><td>'.wmt_h(substr($s['start_time'],0,5)).'-'.wmt_h(substr($s['end_time'],0,5)).'</td><td>'.wmt_h(implode('; ',$b)).'</td></tr>'; } echo '</table></div><div class="card"><h2>8AM-5PM Coverage Plan</h2><table><tr><th>Time</th><th>Grocery</th><th>GM</th><th>Off</th><th>Floater</th><th>Flex</th><th>Watch</th></tr>'; foreach($pl['rows'] as $r){ echo '<tr><td>'.wmt_nice($r[0]).'-'.wmt_nice($r[1]).'</td><td>'.($r[2]?wmt_h($r[2]):'<span class="bad">Uncovered</span>').'</td><td>'.($r[3]?wmt_h($r[3]):'<span class="bad">Uncovered</span>').'</td><td>'.wmt_h($r[5]).'</td><td>'.wmt_h($r[4]).'</td><td>'.wmt_h($r[6]).'</td><td>'.($r[7]?'<span class="bad">'.wmt_h($r[7]).'</span>':'<span class="ok">Covered</span>').'</td></tr>'; } echo '</table></div>'; }
function wmt_dashboard($pdo,$msg){ $d=$_GET['date']??date('Y-m-d'); $pl=wmt_plan($pdo,$d); wmt_head('Dashboard'); if($msg)echo '<div class="card">'.wmt_h($msg).'</div>'; echo '<div class="card no-print"><form><input type="date" name="date" value="'.wmt_h($d).'"> <button>Load</button> <a class="btn" href="?v=mgmt&date='.wmt_h($d).'">Print Mgmt</a> <a class="btn" href="?v=ta&date='.wmt_h($d).'">Print TA</a></form></div><div class="card"><h1>Daily Coverage Review - '.wmt_h($d).'</h1><div class="grid"><div class="kpi">Coverage<b>'.wmt_h($pl['pct']).'%</b></div><div class="kpi">Gap minutes<b class="'.($pl['gap']?'bad':'ok').'">'.wmt_h($pl['gap']).'</b></div><div class="kpi">Floater minutes<b>'.wmt_h($pl['float']).'</b></div><div class="kpi">Scheduled<b>'.count($pl['shifts']).'</b></div></div></div>'; wmt_tables($pl); echo '</main>'; }
function wmt_import_page($msg){ wmt_head('Import'); if($msg)echo '<div class="card">'.wmt_h($msg).'</div>'; echo '<div class="card"><h1>Import</h1><p>CSV header: date,name,team,role_type,start,end,preferred_door,notes</p><form method="post"><input type="hidden" name="form" value="csv"><textarea name="csv">date,name,team,role_type,start,end,preferred_door,notes\n2026-06-15,Example TA,Services,AP Service TA,08:00,17:00,Grocery,</textarea><br><button>Import CSV</button></form></div><div class="card"><h2>JSON</h2><form method="post"><input type="hidden" name="form" value="json"><textarea name="payload">{"replace_schedule_dates":["2026-06-15"],"schedule":[{"date":"2026-06-15","name":"Example TA","team":"Services","role_type":"AP Service TA","start":"08:00","end":"17:00","preferred_door":"Grocery"}]}</textarea><br><button>Import JSON</button></form></div></main>'; }
function wmt_week($pdo){ $d=new DateTime($_GET['date']??date('Y-m-d')); $d->modify('monday this week'); wmt_head('Week'); echo '<div class="card"><h1>Weekly Summary</h1><table><tr><th>Date</th><th>Coverage</th><th>Gap</th><th>People</th></tr>'; for($i=0;$i<7;$i++){ $day=(clone $d)->modify('+'.$i.' day')->format('Y-m-d'); $pl=wmt_plan($pdo,$day); echo '<tr><td><a href="?date='.$day.'">'.$day.'</a></td><td>'.$pl['pct'].'%</td><td class="'.($pl['gap']?'bad':'ok').'">'.$pl['gap'].'</td><td>'.count($pl['shifts']).'</td></tr>'; } echo '</table></div></main>'; }
try{ $pdo=wmt_db(); wmt_schema($pdo); wmt_auth($pdo); if(isset($_GET['export'])){ header('Content-Type: application/json'); echo json_encode(array('settings'=>$pdo->query('SELECT * FROM wmt_settings')->fetchAll(),'associates'=>$pdo->query('SELECT * FROM wmt_associates')->fetchAll(),'schedule'=>$pdo->query('SELECT * FROM wmt_shifts')->fetchAll(),'tasks'=>$pdo->query('SELECT * FROM wmt_tasks')->fetchAll()),JSON_PRETTY_PRINT); exit; } $msg=wmt_import($pdo); $v=$_GET['v']??'dashboard'; if($v==='import')wmt_import_page($msg); elseif($v==='week')wmt_week($pdo); else wmt_dashboard($pdo,$msg); } catch(Throwable $e){ http_response_code(500); echo '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><body style="font-family:system-ui;background:#f4f1ea"><div style="max-width:900px;margin:40px auto;background:white;padding:24px;border-radius:16px"><h1>WMT setup error</h1><p>The PHP file loaded, but setup failed.</p><pre>'.wmt_h($e->getMessage()).'</pre><p>Try adding <code>?debug=1</code> to the URL.</p></div>'; }
