<?php
error_reporting(E_ALL);
ini_set('display_errors', isset($_GET['debug']) ? '1' : '0');
ini_set('log_errors', '1');
session_start();
require_once __DIR__.'/wmt-engine.php';

/* index.php keeps its dashboard / week / print views unchanged; the planning
 * engine now lives in wmt-engine.php. These thin adapters map the legacy names
 * this page uses onto the shared wmt_ functions, so there is one engine across
 * index.php, tasks.php and assignments.php instead of three copies. */
function e($s){ return wmt_e($s); }
function mins($t){ return wmt_mins($t); }
function nice($m){ return wmt_nice($m); }
function team_of($r){ return wmt_team_of($r); }
function priority_num($p){ return wmt_priority_num($p); }
function db(){ return wmt_db(); }
function schema($p){ wmt_schema($p); }
function setting($p,$k,$d=null){ return wmt_setting($p,$k,$d); }
function setg($p,$k,$v){ wmt_set_setting($p,$k,$v); }
function up_assoc($p,$r){ return wmt_up_assoc($p,$r); }
function import_payload($p,$j){ return wmt_import_payload($p,$j); }
function import_current($p){ return wmt_import_current($p); }
function auto_seed($p){ wmt_auto_seed($p); }
function plan($p,$d){ return wmt_plan($p,$d); }
function compress_rows($rows,$keys){ return wmt_compress_rows($rows,$keys); }
function same_block($a,$b,$keys){ return wmt_same_block($a,$b,$keys); }
function person_blocks($pl,$name){ return wmt_person_blocks($pl,$name); }
function theme_css(){ return wmt_theme_css(); }
function task_rows($p){ return wmt_task_rows($p); }

function login_page($title,$form){ echo '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.e($title).'</title><style>'.theme_css().' .box{max-width:420px;margin:12vh auto;background:white;padding:28px;border-radius:18px;border:1px solid var(--border);box-shadow:0 4px 18px rgba(0,0,0,.08)}input,button{width:100%;padding:12px;border-radius:10px;margin-top:10px;box-sizing:border-box}</style><div class="box"><h1>'.e($title).'</h1><form method="post"><input type="hidden" name="form" value="'.e($form).'"><input type="password" name="password" placeholder="Password" required><button>Continue</button></form></div>'; exit; }
function auth($p){ $hash=setting($p,'admin_hash'); if(!$hash){ if(($_POST['form']??'')==='setpass' && strlen($_POST['password']??'')>=8){ setg($p,'admin_hash',password_hash($_POST['password'],PASSWORD_DEFAULT)); $_SESSION['wmt']=1; header('Location:index.php'); exit; } login_page('Create WMT Admin Password','setpass'); } if(isset($_GET['logout'])){ unset($_SESSION['wmt']); header('Location:index.php'); exit; } if(($_POST['form']??'')==='login' && password_verify($_POST['password']??'',$hash)){ $_SESSION['wmt']=1; header('Location:index.php'); exit; } if(empty($_SESSION['wmt'])) login_page('AP Services Login','login'); }
function handle_post($p){ if($_SERVER['REQUEST_METHOD']!=='POST') return ''; $f=$_POST['form']??''; if($f==='current_week') return import_current($p); if($f==='json') return import_payload($p,json_decode($_POST['payload']??'',true)); if($f==='csv'){ $lines=preg_split('/\r\n|\n|\r/',trim($_POST['csv']??'')); if(!$lines || count($lines)<2) return 'No CSV rows found.'; $h=array_map('strtolower',array_map('trim',str_getcsv(array_shift($lines)))); $c=0; foreach($lines as $line){ if(trim($line)==='') continue; $v=str_getcsv($line); $r=array(); foreach($h as $i=>$k){ $r[$k]=$v[$i]??''; } if(empty($r['date'])||empty($r['name'])||empty($r['start'])||empty($r['end'])) continue; $id=up_assoc($p,$r); $p->prepare('INSERT INTO wmt_shifts(work_date,associate_id,associate_name,team,role_type,start_time,end_time,notes) VALUES(?,?,?,?,?,?,?,?)')->execute(array($r['date'],$id,$r['name'],$r['team']??'Services',$r['role_type']??'AP Service TA',$r['start'],$r['end'],$r['notes']??null)); $c++; } return 'Imported '.$c.' CSV rows'; } if($f==='turnin'){ foreach($_POST['task']??array() as $t){ $p->prepare('INSERT INTO wmt_turnins(work_date,task_name,status,completed_by,notes,manager_signoff) VALUES(?,?,?,?,?,?)')->execute(array($_POST['date'],$t['name'],$t['status'],$t['by'],$t['notes'],$_POST['mgr']??null)); } if(trim($_POST['exceptions']??'')!=='') $p->prepare('INSERT INTO wmt_exceptions(work_date,type,severity,notes,reported_to) VALUES(?,?,?,?,?)')->execute(array($_POST['date'],'Daily note','Medium',$_POST['exceptions'],$_POST['mgr']??null)); return 'Turn-in saved'; } return ''; }

function head_html($title){ echo '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.e($title).'</title><style>'.theme_css().'</style><link rel="stylesheet" href="walmart-theme.css"><div class="top no-print"><div class="wrap"><b>AP Services Tool</b><div class="nav"><a href="index.php">Dashboard</a><a href="assignments.php">Assignments</a><a href="tasks.php">Door Tasks</a><a href="?v=week">Week</a><a href="?v=import">Import</a><a href="import_html.php">HTML Import</a><a href="?v=turnin">Turn-In</a><a href="?export=json">Export</a><a href="?logout=1">Logout</a></div></div></div><main class="wrap">'; }
function foot_html(){ echo '</main>'; }
function shift_table($pl){ echo '<div class="card"><h2>Who is here</h2><table><tr><th>Name</th><th>Team</th><th>Role</th><th>Shift</th><th>Optimized Break/Lunch Plan</th><th>Preferred Door</th></tr>'; $by=array(); foreach($pl['break_plan']['events'] as $ev){ $by[$ev['associate']][]=$ev['type'].' '.nice($ev['start']).'-'.nice($ev['end']); } foreach($pl['shifts'] as $s){ $n=$s['associate_name']; echo '<tr><td><b>'.e($n).'</b></td><td>'.e($s['team']).'</td><td>'.e($s['role_type']).'</td><td>'.e(substr($s['start_time'],0,5)).'-'.e(substr($s['end_time'],0,5)).'</td><td>'.e(implode('; ',$by[$n]??array())?:'None planned').'</td><td>'.e($s['preferred_door']??'Either').'</td></tr>'; } echo '</table></div>'; }
function plan_table($pl,$compressed=true){ $rows=$compressed?compress_rows($pl['rows'],array('grocery','gm','floater','off','flex','watch')):$pl['rows']; echo '<div class="card"><h2>8AM-5PM Coverage Plan '.($compressed?'<span class="muted small">compressed by change</span>':'<span class="muted small">15-minute grid</span>').'</h2><table><tr><th>Time</th><th>Grocery</th><th>GM</th><th>Break/Lunch</th><th>Floater / Tasks</th><th>Flex</th><th>Watch</th></tr>'; foreach($rows as $r){ echo '<tr><td class="time">'.nice($r['start']).'-'.nice($r['end']).'</td><td>'.($r['grocery']?e($r['grocery']):'<span class="bad">Uncovered</span>').'</td><td>'.($r['gm']?e($r['gm']):'<span class="bad">Uncovered</span>').'</td><td>'.e($r['off']?:'-').'</td><td>'.e($r['floater']?:'-').'</td><td>'.e($r['flex']?:'-').'</td><td>'.($r['watch']?'<span class="bad">'.e($r['watch']).'</span>':'<span class="ok">Covered</span>').'</td></tr>'; } echo '</table></div>'; }
function break_warnings($pl){ if(empty($pl['break_plan']['warnings'])) return; echo '<div class="card"><h2>Break/Lunch Stagger Notes</h2>'; foreach(array_unique($pl['break_plan']['warnings']) as $w){ echo '<div class="warn">'.e($w).'</div>'; } echo '</div>'; }
function dashboard($p,$msg){ $d=$_GET['date']??date('Y-m-d'); $pl=plan($p,$d); head_html('Dashboard'); if($msg) echo '<div class="card">'.e($msg).'</div>'; echo '<div class="card no-print"><form><input type="date" name="date" value="'.e($d).'"> <button>Load</button> <a class="btn" href="?v=mgmt&date='.e($d).'">Print Mgmt</a> <a class="btn" href="?v=ta&date='.e($d).'">Print TA</a> <a class="btn" href="?v=grid&date='.e($d).'">15-min Grid</a> <a class="btn" href="?v=turnin&date='.e($d).'">Turn-In</a></form></div><div class="card"><h1 class="print-title">Daily Coverage Review - '.e($d).'</h1><p class="muted">Walmart-blue operational view. Engine plans in 15-minute slots; display compresses into blocks that only change when assignment, break, flex, or gap status changes.</p><div class="grid"><div class="kpi">Coverage<b>'.e($pl['pct']).'%</b></div><div class="kpi">Gap minutes<b class="'.($pl['gap']?'bad':'ok').'">'.e($pl['gap']).'</b></div><div class="kpi">Floater minutes<b>'.e($pl['float']).'</b></div><div class="kpi">Scheduled<b>'.count($pl['shifts']).'</b></div></div></div>'; shift_table($pl); break_warnings($pl); plan_table($pl,true); foot_html(); }
function week_view($p){ $d=new DateTime($_GET['date']??date('Y-m-d')); $d->modify('monday this week'); head_html('Week'); echo '<div class="card"><h1>Weekly Summary</h1><table><tr><th>Date</th><th>Coverage</th><th>Gap</th><th>People</th><th>Print</th></tr>'; for($i=0;$i<7;$i++){ $day=(clone $d)->modify('+'.$i.' day')->format('Y-m-d'); $pl=plan($p,$day); echo '<tr><td><b>'.e($day).'</b></td><td>'.e($pl['pct']).'%</td><td class="'.($pl['gap']?'bad':'ok').'">'.e($pl['gap']).'</td><td>'.count($pl['shifts']).'</td><td><a href="?date='.$day.'">View</a> · <a href="?v=mgmt&date='.$day.'">Mgmt</a> · <a href="?v=ta&date='.$day.'">TA</a> · <a href="?v=grid&date='.$day.'">Grid</a> · <a href="?v=turnin&date='.$day.'">Turn-in</a></td></tr>'; } echo '</table></div>'; foot_html(); }
function import_view($msg){ head_html('Import'); if($msg) echo '<div class="card">'.e($msg).'</div>'; echo '<div class="card"><h1>Import data</h1><p>Use the HTML importer for saved Workforce Planning Portal files, or paste CSV/JSON.</p><p><a class="btn" href="import_html.php">Upload Scheduler HTML</a></p><form method="post"><input type="hidden" name="form" value="current_week"><button>Import current screenshot week</button></form></div><div class="card"><h2>CSV</h2><p class="muted">Header: date,name,team,role_type,start,end,preferred_door,notes</p><form method="post"><input type="hidden" name="form" value="csv"><textarea name="csv">date,name,team,role_type,start,end,preferred_door,notes\n2026-06-15,Example TA,Services,AP Service TA,08:00,17:00,Grocery,</textarea><button>Import CSV</button></form></div><div class="card"><h2>JSON</h2><form method="post"><input type="hidden" name="form" value="json"><textarea name="payload">{\n  "replace_schedule_dates":["2026-06-15"],\n  "schedule":[{"date":"2026-06-15","name":"Example TA","team":"Services","role_type":"AP Service TA","start":"08:00","end":"17:00","preferred_door":"Grocery"}]\n}</textarea><button>Import JSON</button></form></div>'; foot_html(); }
function turnin_view($p,$msg){ $d=$_GET['date']??date('Y-m-d'); $tasks=task_rows($p); head_html('Turn-In'); if($msg) echo '<div class="card">'.e($msg).'</div>'; echo '<div class="card"><h1 class="print-title">Daily Turn-In / Sign-Off - '.e($d).'</h1><form method="post"><input type="hidden" name="form" value="turnin"><input type="hidden" name="date" value="'.e($d).'"><table><tr><th>Task</th><th>Status</th><th>Completed By</th><th>Notes</th></tr>'; foreach($tasks as $i=>$t){ echo '<tr><td><b>'.e($t['name']).'</b><br><span class="muted small">'.e($t['category'].' · '.$t['priority'].' · weight '.$t['weight']).'</span><input type="hidden" name="task['.$i.'][name]" value="'.e($t['name']).'"></td><td><select name="task['.$i.'][status]"><option>Not Started</option><option>Completed</option><option>Missed</option><option>Deferred</option><option>N/A</option></select></td><td><input name="task['.$i.'][by]"></td><td><input name="task['.$i.'][notes]"></td></tr>'; } echo '</table><p>Exceptions / weather / door gaps / suspicious activity / equipment issues<br><textarea name="exceptions"></textarea></p><p>Manager sign-off <input name="mgr"></p><button class="no-print">Save</button></form></div>'; foot_html(); }
function mgmt_view($p){ $d=$_GET['date']??date('Y-m-d'); $pl=plan($p,$d); head_html('Management Print'); echo '<div class="card"><h1 class="print-title">Management Daily Coverage Review - '.e($d).'</h1><p><b>Rules:</b> Services own doors. Breaks/lunches are staggered coverage-first. Ops flex only when two Ops are available and not 10AM-12PM. TL max 15 minutes/day. Investigator never flexes.</p><p><b>Coverage:</b> '.e($pl['pct']).'% · <b>Gap minutes:</b> '.e($pl['gap']).' · <b>Floater minutes:</b> '.e($pl['float']).'</p></div>'; shift_table($pl); break_warnings($pl); plan_table($pl,true); foot_html(); }
function grid_view($p){ $d=$_GET['date']??date('Y-m-d'); $pl=plan($p,$d); head_html('15-min Grid'); echo '<div class="card"><h1>15-minute Planning Grid - '.e($d).'</h1><p class="muted">This is the raw planning layer. Print views use compressed blocks.</p></div>'; plan_table($pl,false); foot_html(); }
function ta_view($p){ $d=$_GET['date']??date('Y-m-d'); $pl=plan($p,$d); head_html('TA Print'); $names=array(); foreach($pl['shifts'] as $s){ if(team_of($s)==='Services') $names[$s['associate_name']]=$s; } if(!$names) echo '<div class="card"><h1>No AP Services TAs scheduled for '.e($d).'</h1></div>'; foreach($names as $name=>$s){ echo '<div class="card page"><h1 class="print-title">Associate Position Sheet - '.e($name).'</h1><p><b>Date:</b> '.e($d).' <b>Shift:</b> '.e(substr($s['start_time'],0,5)).'-'.e(substr($s['end_time'],0,5)).'</p><p><b>Do not leave your post until relieved or directed.</b> If relief does not arrive, contact leadership/AP.</p><table><tr><th>Time</th><th>Your Position</th><th>Handoff</th><th>Notes</th></tr>'; foreach(person_blocks($pl,$name) as $r){ echo '<tr><td class="time">'.nice($r['start']).'-'.nice($r['end']).'</td><td><b>'.e($r['pos']).'</b></td><td>'.e($r['handoff']).'</td><td>'.e($r['notes']).'</td></tr>'; } echo '</table></div>'; } foot_html(); }

try{
  $p=db(); schema($p); auth($p); auto_seed($p);
  if(isset($_GET['export'])){ header('Content-Type: application/json'); echo json_encode(array('settings'=>$p->query('SELECT * FROM wmt_settings')->fetchAll(),'associates'=>$p->query('SELECT * FROM wmt_associates')->fetchAll(),'schedule'=>$p->query('SELECT * FROM wmt_shifts ORDER BY work_date,start_time')->fetchAll(),'tasks'=>$p->query('SELECT * FROM wmt_tasks')->fetchAll()), JSON_PRETTY_PRINT); exit; }
  $msg=handle_post($p); $v=$_GET['v']??'dashboard';
  if($v==='week') week_view($p); elseif($v==='import') import_view($msg); elseif($v==='turnin') turnin_view($p,$msg); elseif($v==='mgmt') mgmt_view($p); elseif($v==='ta') ta_view($p); elseif($v==='grid') grid_view($p); else dashboard($p,$msg);
}catch(Throwable $ex){ http_response_code(500); echo '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>'.theme_css().'</style><body><div class="card" style="max-width:900px;margin:40px auto"><h1>WMT setup error</h1><p>The PHP file loaded, but setup failed.</p><pre>'.e($ex->getMessage()).'</pre><p>Try adding <code>?debug=1</code> to the URL and send the exact message.</p></div>'; }
