<?php
error_reporting(E_ALL);
ini_set('display_errors', isset($_GET['debug']) ? '1' : '0');
session_start();

function h($s){return htmlspecialchars((string)$s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function has($s,$n){return strpos((string)$s,(string)$n)!==false;}
function mins($t){if(!preg_match('/^(\d{1,2}):(\d{2})/',(string)$t,$m))return 0;return ((int)$m[1]*60)+(int)$m[2];}
function nice($m){$m=(($m%1440)+1440)%1440;$h=(int)floor($m/60);$ap=$h>=12?'PM':'AM';$hh=$h%12;if(!$hh)$hh=12;return $hh.':'.sprintf('%02d',$m%60).$ap;}
function team_of($r){$x=strtolower(($r['team']??'').' '.($r['role_type']??''));if(has($x,'invest'))return'Investigator';if(has($x,'lead')||has($x,'tl'))return'Team Lead';if(has($x,'ops')||has($x,'operation'))return'Ops';return'Services';}
function priority_num($p){$p=strtolower((string)$p);if($p==='critical')return 1;if($p==='high')return 2;if($p==='medium')return 3;return 4;}
function db(){static $p=null;if($p)return$p;foreach(array(__DIR__.'/../../database.php',__DIR__.'/../database.php')as$f){if(is_file($f)){require_once$f;break;}}if(function_exists('ho_db'))$p=ho_db();elseif(isset($GLOBALS['pdo'])&&$GLOBALS['pdo']instanceof PDO)$p=$GLOBALS['pdo'];else throw new Exception('No database connection found.');$p->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$p->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);return$p;}
function setting($p,$k,$d=null){try{$s=$p->prepare('SELECT v FROM wmt_settings WHERE k=?');$s->execute(array($k));$v=$s->fetchColumn();return$v===false?$d:$v;}catch(Exception$e){return$d;}}
function setup($p){$p->exec("CREATE TABLE IF NOT EXISTS wmt_task_assignments(id INT AUTO_INCREMENT PRIMARY KEY,work_date DATE NOT NULL,side VARCHAR(20) NOT NULL,task_name VARCHAR(180) NOT NULL,assigned_to VARCHAR(120),priority VARCHAR(20),status VARCHAR(30) NOT NULL DEFAULT 'Assigned',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY one_daily_task(work_date,side,task_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
function auth($p){$s=$p->prepare('SELECT v FROM wmt_settings WHERE k=?');$s->execute(array('admin_hash'));$hash=$s->fetchColumn();if(!$hash){header('Location:index.php');exit;}if(($_POST['form']??'')==='login'&&password_verify($_POST['password']??'',$hash)){$_SESSION['wmt']=1;header('Location:tasks.php');exit;}if(empty($_SESSION['wmt'])){echo'<!doctype html><title>Login</title><link rel="stylesheet" href="walmart-theme.css"><div class="card" style="max-width:420px;margin:12vh auto"><h1>AP Services Login</h1><form method="post"><input type="hidden" name="form" value="login"><input type="password" name="password" placeholder="Password"><button>Continue</button></form></div>';exit;}}
function shifts($p,$d){$q=$p->prepare('SELECT s.*,a.preferred_door,a.can_cover,a.reliability FROM wmt_shifts s LEFT JOIN wmt_associates a ON a.id=s.associate_id WHERE work_date=? ORDER BY start_time,associate_name');$q->execute(array($d));return$q->fetchAll();}
function shift_span($s){$st=mins(substr($s['start_time'],0,5));$en=mins(substr($s['end_time'],0,5));if($en<=$st)$en+=1440;return array($st,$en,$en-$st);}
function covers($s,$a,$b){$x=shift_span($s);return$a>=$x[0]&&$b<=$x[1];}
function raw_breaks($s,$slot=15){$x=shift_span($s);$st=$x[0];$en=$x[1];$dur=$x[2];$out=array();if($dur>=480){$q=$dur/4;$out[]=array('Break 1',(int)(round(($st+$q-8)/$slot)*$slot),15);$out[]=array('Lunch',(int)(round(($st+2*$q-30)/$slot)*$slot),60);$out[]=array('Break 2',(int)(round(($st+3*$q-8)/$slot)*$slot),15);}elseif($dur>=360){$out[]=array('Break',(int)(round(($st+$dur/3-8)/$slot)*$slot),15);$out[]=array('Lunch',(int)(round(($st+$dur*2/3-15)/$slot)*$slot),30);}elseif($dur>=240){$out[]=array('Break',(int)(round(($st+$dur/2-8)/$slot)*$slot),15);}return$out;}
function off($s,$t,$slot){foreach(raw_breaks($s,$slot)as$b){if($t>=$b[1]&&$t<$b[1]+$b[2])return$b[0];}return'';}
function pick($c,$door,$used,$counts){$best=null;$score=999999;foreach($c as$r){$n=$r['associate_name'];if(isset($used[$n]))continue;$s=($counts[$n]??0)*10-((float)($r['reliability']??3))*2;$pref=$r['preferred_door']??'Either';if($pref===$door)$s-=20;elseif($pref==='Either')$s-=5;if($s<$score){$score=$s;$best=$r;}}return$best;}
function plan_day($p,$d){$sh=shifts($p,$d);$slot=(int)setting($p,'slot_minutes',15);if($slot<5)$slot=15;$start=mins(setting($p,'triage_start','08:00'));$end=mins(setting($p,'triage_end','17:00'));$counts=array();$rows=array();$sideMin=array('Grocery'=>array(),'GM'=>array());for($t=$start;$t<$end;$t+=$slot){$svc=array();foreach($sh as$s){if(team_of($s)!=='Services'||!(int)($s['can_cover']??1))continue;if(!covers($s,$t,$t+$slot))continue;if(off($s,$t,$slot))continue;$svc[]=$s;}$used=array();$g=pick($svc,'Grocery',$used,$counts);if($g){$used[$g['associate_name']]=1;$counts[$g['associate_name']]=($counts[$g['associate_name']]??0)+1;$sideMin['Grocery'][$g['associate_name']]=($sideMin['Grocery'][$g['associate_name']]??0)+$slot;}$gm=pick($svc,'GM',$used,$counts);if($gm){$used[$gm['associate_name']]=1;$counts[$gm['associate_name']]=($counts[$gm['associate_name']]??0)+1;$sideMin['GM'][$gm['associate_name']]=($sideMin['GM'][$gm['associate_name']]??0)+$slot;}$rows[]=array('start'=>$t,'end'=>$t+$slot,'Grocery'=>$g?$g['associate_name']:'','GM'=>$gm?$gm['associate_name']:'');}return array('rows'=>$rows,'side_minutes'=>$sideMin,'shifts'=>$sh);}
function block_times($rows,$side,$name){$blocks=array();foreach($rows as$r){if($r[$side]!==$name)continue;$i=count($blocks)-1;if($i>=0&&$blocks[$i]['end']===$r['start'])$blocks[$i]['end']=$r['end'];else$blocks[]=array('start'=>$r['start'],'end'=>$r['end']);}return$blocks;}
function tasks($p){$rows=$p->query('SELECT * FROM wmt_tasks WHERE active=1')->fetchAll();$out=array();foreach($rows as$r){$n=strtolower($r['name']);if(has($n,'suspicious')||has($n,'inclement')||has($n,'report'))continue;$out[]=$r;}usort($out,function($a,$b){$pa=priority_num($a['priority']);$pb=priority_num($b['priority']);if($pa===$pb)return(int)$b['weight']-(int)$a['weight'];return$pa-$pb;});return$out;}
function assign_tasks($p,$d){$pl=plan_day($p,$d);$tasks=tasks($p);$assign=array();foreach(array('Grocery','GM')as$side){$owners=$pl['side_minutes'][$side];arsort($owners);$names=array_keys($owners);$load=array();foreach($names as$n)$load[$n]=0;foreach($tasks as$t){$chosen='Unassigned';if($names){$best=null;$score=999999;foreach($names as$n){$s=($load[$n]??0)-(($owners[$n]??0)/60);if($s<$score){$score=$s;$best=$n;}}$chosen=$best;$load[$chosen]=($load[$chosen]??0)+(int)$t['weight'];}$blocks=$chosen!=='Unassigned'?block_times($pl['rows'],$side,$chosen):array();$window=$blocks?(nice($blocks[0]['start']).'-'.nice($blocks[0]['end'])):'No clean 8-5 owner';$assign[]=array('side'=>$side,'task'=>$t['name'],'priority'=>$t['priority'],'weight'=>$t['weight'],'assigned_to'=>$chosen,'window'=>$window,'notes'=>$chosen==='Unassigned'?'No AP Service TA owns this side during the 8-5 planning window.':'Owns '.$side.' coverage block; complete when traffic/coverage allows without leaving post unsecured.');}}return array($assign,$pl);}
function save_assignments($p,$d,$assign){$p->prepare('DELETE FROM wmt_task_assignments WHERE work_date=?')->execute(array($d));$q=$p->prepare('INSERT INTO wmt_task_assignments(work_date,side,task_name,assigned_to,priority,notes) VALUES(?,?,?,?,?,?)');foreach($assign as$a)$q->execute(array($d,$a['side'],$a['task'],$a['assigned_to'],$a['priority'],$a['notes'].' Suggested window: '.$a['window']));return count($assign);}
function head_html($title){echo'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.h($title).'</title><link rel="stylesheet" href="walmart-theme.css"><div class="top no-print"><div class="wrap"><b>AP Services Tool</b><div class="nav"><a href="index.php">Dashboard</a><a href="tasks.php">Daily Tasks</a><a href="index.php?v=week">Week</a><a href="index.php?v=turnin">Turn-In</a></div></div></div><main class="wrap">';}
function foot(){echo'</main>';}
try{$p=db();setup($p);auth($p);$d=$_GET['date']??date('Y-m-d');$msg='';list($assign,$pl)=assign_tasks($p,$d);if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['form']??'')==='save'){$msg='Saved '.save_assignments($p,$d,$assign).' task assignments for '.$d.'.';}head_html('Daily Door Tasks');if($msg)echo'<div class="card"><b>'.h($msg).'</b></div>';echo'<div class="card no-print"><form><input type="date" name="date" value="'.h($d).'"><button>Load</button></form><form method="post"><input type="hidden" name="form" value="save"><button>Save these assignments</button></form></div>';echo'<div class="card"><h1 class="print-title">Daily Door Task Assignments - '.h($d).'</h1><p class="muted">Each daily task is duplicated for Grocery and GM. The system assigns the side task to the AP Service TA who owns the most coverage on that side, then balances task weight across same-side owners. These are ownership assignments, not permission to abandon a door.</p></div>';foreach(array('Grocery','GM')as$side){echo'<div class="card"><h2>'.h($side).' side tasks</h2><table><tr><th>Task</th><th>Assigned To</th><th>Priority</th><th>Suggested Window</th><th>Instruction</th></tr>';foreach($assign as$a){if($a['side']!==$side)continue;echo'<tr><td><b>'.h($a['task']).'</b></td><td>'.h($a['assigned_to']).'</td><td>'.h($a['priority']).'</td><td>'.h($a['window']).'</td><td>'.h($a['notes']).'</td></tr>';}echo'</table></div>';}echo'<div class="card"><h2>Side ownership minutes</h2><table><tr><th>Side</th><th>Associate</th><th>8-5 Owner Minutes</th></tr>';foreach($pl['side_minutes']as$side=>$mins){arsort($mins);foreach($mins as$n=>$m)echo'<tr><td>'.h($side).'</td><td>'.h($n).'</td><td>'.h($m).'</td></tr>';}echo'</table></div>';foot();}catch(Throwable$e){http_response_code(500);head_html('Task setup error');echo'<div class="card"><h1>Task setup error</h1><pre>'.h($e->getMessage()).'</pre></div>';foot();}
